add_drink:
  name: Add drink
  description: Increment drink counter for a user
  fields:
    user:
      description: User name
      example: Alice
    drink:
      description: Drink name
      example: beer
remove_drink:
  name: Remove drink
  description: Decrement drink counter for a user
  fields:
    user:
      description: User name
      example: Alice
    drink:
      description: Drink name
      example: beer
adjust_count:
  name: Adjust count
  description: Set drink count for a user
  fields:
    user:
      description: User name
      example: Alice
    drink:
      description: Drink name
      example: beer
    count:
      description: Desired drink count
      example: 3
reset_counters:
  name: Reset counters
  description: Reset counters for a user. If no user is specified, reset all.
  fields:
    user:
      description: User name
      example: Alice
      required: false
